all: README.md
 
README.md: guessinggame.sh
        echo "# Guessinggame program" > README.md
        echo "## " $$(date) >> README.md
        wc -l guessinggame.sh >> README.md
clean:
        rm README.md